version: '2'

services:
  redis:
    image: redis:latest

  front:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - redis
      - back
    volumes:
      - ./backend/dashboard:/opt/project
    command: python manage.py runserver 0.0.0.0:8888
    links:
      - redis
      - back
    ports:
      - "8888:8888"

  back:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - redis
    volumes:
      - ./backend/backend:/opt/project
    command: python manage.py runserver 0.0.0.0:7777
    links:
      - redis
    ports:
      - "7777:7777"

